### ISSUE TITLE
RabbitMQ Container crashes on some servers during startup

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#80]
09-May-2018 12:43:02.622 INFO [pool-1-thread-1] kieker.common.logging.LogImplSLF4JLogging.info Terminating analysis.
09-May-2018 12:43:02.622 SEVERE [pool-1-thread-1] kieker.common.logging.LogImplSLF4JLogging.error Error during shutdown.
 java.lang.NoSuchMethodError: com.rabbitmq.client.Connection.close()V
        at kieker.analysis.plugin.reader.amqp.ChunkingAmqpReader.onTermination(ChunkingAmqpReader.java:134)
        at kieker.analysis.plugin.reader.newio.RawDataReaderPlugin.terminateReader(RawDataReaderPlugin.java:186)
        at kieker.analysis.plugin.reader.newio.RawDataReaderPlugin.terminate(RawDataReaderPlugin.java:182)
        at kieker.analysis.plugin.AbstractPlugin.shutdown(AbstractPlugin.java:578)
        at kieker.analysis.AnalysisController.terminate(AnalysisController.java:550)
        at kieker.analysis.AnalysisController.terminate(AnalysisController.java:529)
        at kieker.analysis.AnalysisController.run(AnalysisController.java:509)
        at tools.descartes.teastore.kieker.rabbitmq.LogReaderDaemon.run(LogReaderDaemon.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by SimonEismann** [comment]
Seems fixed in commit 0ffa6493a3489569b479d7a3266f2b5a6af8385c

**Comment by SimonEismann** [comment]
Was unfortunately not fixed, needs to be fixed ASAP

**Comment by SimonEismann** [comment]
Fixed in f6178db778695b52aada39bcf57e1e3fb9843728 by removing surplus dependency causing classloading issues
